### ISSUE TITLE
php7.2 apache libzip warning

### ISSUE THREAD

**Issue by Anuovec** [touch4it/docker-php7-apache-symfony#5]
```
configure: WARNING: ========================================================
configure: WARNING: Use of bundled libzip is deprecated and will be removed.
configure: WARNING: Some features such as encryption and bzip2 are not available.
configure: WARNING: Use system library and --with-libzip is recommended.
configure: WARNING: ========================================================
```

**Comment by shorif2000** [comment]
any updates on this. i ma gettign same message when i try to configure using

`./configure  --enable-fpm  --with-fpm-systemd  --enable-zip --with-zlib  --with-curl  --with-gd  --with-openssl  --with-ldap  --with-libdir=lib64  --enable-mbstring  --prefix=/opt/SP/php-7.2.14  --with-pcre-regex  --quiet`

i am on `centos 7.5.1804` building `php-7.2.14`

**Comment by vsulak** [comment]
> any updates on this. i ma gettign same message when i try to configure using
> 
> `./configure --enable-fpm --with-fpm-systemd --enable-zip --with-zlib --with-curl --with-gd --with-openssl --with-ldap --with-libdir=lib64 --enable-mbstring --prefix=/opt/SP/php-7.2.14 --with-pcre-regex --quiet`
> 
> i am on `centos 7.5.1804` building `php-7.2.14`

Try installing `libzip-devel` and `zip` packages before configuring FPM and replace `--with-zlib` by `--with-libzip`

The problem should be that PHP bundles old libzip and needs the OS to provide newer one. In my case the problem was solved by php team upgrading base image from Debian Jessie (libzip 0.11) to Stretch (libzip 1.1)
